name: Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  PROTOSTAR_VERSION: "0.3.2"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"] # Cairo was tested with this version
    steps:
      - uses: actions/checkout@v3

      - name: Install Protostar
        shell: bash
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash  -s -- -v $PROTOSTAR_VERSION

      - name: Install submodules
        shell: bash
        run: |
          export PATH="$PATH:/home/runner/.protostar/dist/protostar" && protostar install

      - name: Build
        shell: bash
        run: |
          export PATH="$PATH:/home/runner/.protostar/dist/protostar" && protostar build

      - name: Run tests
        run: |
          export PATH="$PATH:/home/runner/.protostar/dist/protostar" && protostar test ./tests
